version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.1.1
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ubuntu_ami.json
  build-base:
    docker:
      - image: hashicorp/packer:1.1.1
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Build AMI
          command: >
            packer build 
            -var 'aws_access_key='${ACCESS_KEY} 
            -var 'aws_secret_key='${SECRET_KEY} 
            -var 'aws_region='${AWS_REGION} 
            -var 'ami_users='${AMI_USERS} 
            -var 'source_ami='${SOURCE_AMI} 
            ubuntu_ami.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build-base:
          requires:
            - validate
